application: newsmap-2015
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /css
  static_dir: css

- url: /
  static_files: index.html
  upload: index\.html

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
